language: java
jdk: oraclejdk8
script:
  - cd arion-core
  - mvn clean install
deploy:
  provider: releases
  api_key: $GITHUB_KEY
  skip_cleanup: true
  file:
    - ./arion-core/target/ArionCore.jar
  on:
    all_branches: true
