version: '3'
services:
  postgres:
    image: postgres:alpine
    volumes:
      - ./server/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=arion
      - POSTGRES_PASSWORD=arion
      - POSTGRES_DB=arion
